### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by asiekierka** [TeamDman/NOVA#1]
Just pointing out that the name of your mod conflicts rather badly with an API that was in the works since January: http://novaapi.net/

What you do with this is up to you.

**Comment by Saereth** [comment]
We discussed this and will be moving to a different name for the 1.8.9 port which will be underway relatively soon to avoid confusion.

**Comment by asiekierka** [comment]
Actually, NOVA the API is dead now so it's no longer a real issue?

2016-01-21 16:41 GMT+01:00 Saereth <notifications@github.com>:
